before_script:
  - rsync --version
  
language: ruby
rvm:
  - 1.9.3
branches:
  only:
    - master
    - production
script: rake travis
env:
  global:
    - secure: "iD47aQ96JvBhmxOoRjwYBDbEWOQw9i4vx46AkD91WKoVr+46s4XGackGXYZKePI8lM2Uw/fEI3Pg/s9dSlc553I4VJi6+3YGlGTdtiuFeOiLR8F28qgJxNaSHM8sH5M5GDCzPHYtkWd3teO5wlwX4gSiYJP5LYzGTYHnEL1mGxA="
    - projectId: "vova"
    - deployment_repository_url: https://github.com/unibrew/test-community.org.git
