language: ruby
rvm:
  - 1.9.3
branches:
  only:
    - master
    - production
script: rake travis
env:
  global:
    - secure: "LYMPw/t5eAD2f9EE/MHVk2xEZyIwTvaDOnOSsuIlRL33KcyvSAi5j0t6+hETZhDxi4iXtXiVlPa8TL/snyLZ3VRnYz2tyH1WvJllIesUcOhgNWoW3a8Ixm2/UYy9TTLl8x+MERImZnjiYywK7/aWsb25Cc+gP/xHm0boMaK/syQ="
    - projectId: "vova"
before_install:
  #- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  #- git remote add -f deployment https://github.com/unibrew/test-community.git
  #- git branch -a
